package com.hengyi.fastim.packet;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface msgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string msgId = 1;</code>
     */
    String getMsgId();
    /**
     * <code>string msgId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>int32 flag = 2;</code>
     */
    int getFlag();

    /**
     * <code>int32 type = 3;</code>
     */
    int getType();

    /**
     * <code>int32 packetType = 4;</code>
     */
    int getPacketType();

    /**
     * <code>int32 extraType = 5;</code>
     */
    int getExtraType();

    /**
     * <code>int32 version = 6;</code>
     */
    int getVersion();

    /**
     * <code>string content = 7;</code>
     */
    String getContent();
    /**
     * <code>string content = 7;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>string send = 8;</code>
     */
    String getSend();
    /**
     * <code>string send = 8;</code>
     */
    com.google.protobuf.ByteString
        getSendBytes();

    /**
     * <code>string receive = 9;</code>
     */
    String getReceive();
    /**
     * <code>string receive = 9;</code>
     */
    com.google.protobuf.ByteString
        getReceiveBytes();

    /**
     * <code>string extraMsg = 10;</code>
     */
    String getExtraMsg();
    /**
     * <code>string extraMsg = 10;</code>
     */
    com.google.protobuf.ByteString
        getExtraMsgBytes();
  }
  /**
   * Protobuf type {@code msg}
   */
  public  static final class msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg)
      msgOrBuilder {
    // Use msg.newBuilder() to construct.
    private msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private msg() {
      msgId_ = "";
      flag_ = 0;
      type_ = 0;
      packetType_ = 0;
      extraType_ = 0;
      version_ = 0;
      content_ = "";
      send_ = "";
      receive_ = "";
      extraMsg_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            case 16: {

              flag_ = input.readInt32();
              break;
            }
            case 24: {

              type_ = input.readInt32();
              break;
            }
            case 32: {

              packetType_ = input.readInt32();
              break;
            }
            case 40: {

              extraType_ = input.readInt32();
              break;
            }
            case 48: {

              version_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              send_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              receive_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              extraMsg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Packet.internal_static_msg_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Packet.internal_static_msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              msg.class, Builder.class);
    }

    public static final int MSGID_FIELD_NUMBER = 1;
    private volatile Object msgId_;
    /**
     * <code>string msgId = 1;</code>
     */
    public String getMsgId() {
      Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <code>string msgId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLAG_FIELD_NUMBER = 2;
    private int flag_;
    /**
     * <code>int32 flag = 2;</code>
     */
    public int getFlag() {
      return flag_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>int32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int PACKETTYPE_FIELD_NUMBER = 4;
    private int packetType_;
    /**
     * <code>int32 packetType = 4;</code>
     */
    public int getPacketType() {
      return packetType_;
    }

    public static final int EXTRATYPE_FIELD_NUMBER = 5;
    private int extraType_;
    /**
     * <code>int32 extraType = 5;</code>
     */
    public int getExtraType() {
      return extraType_;
    }

    public static final int VERSION_FIELD_NUMBER = 6;
    private int version_;
    /**
     * <code>int32 version = 6;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    private volatile Object content_;
    /**
     * <code>string content = 7;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 7;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEND_FIELD_NUMBER = 8;
    private volatile Object send_;
    /**
     * <code>string send = 8;</code>
     */
    public String getSend() {
      Object ref = send_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        send_ = s;
        return s;
      }
    }
    /**
     * <code>string send = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSendBytes() {
      Object ref = send_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        send_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVE_FIELD_NUMBER = 9;
    private volatile Object receive_;
    /**
     * <code>string receive = 9;</code>
     */
    public String getReceive() {
      Object ref = receive_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        receive_ = s;
        return s;
      }
    }
    /**
     * <code>string receive = 9;</code>
     */
    public com.google.protobuf.ByteString
        getReceiveBytes() {
      Object ref = receive_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        receive_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRAMSG_FIELD_NUMBER = 10;
    private volatile Object extraMsg_;
    /**
     * <code>string extraMsg = 10;</code>
     */
    public String getExtraMsg() {
      Object ref = extraMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extraMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string extraMsg = 10;</code>
     */
    public com.google.protobuf.ByteString
        getExtraMsgBytes() {
      Object ref = extraMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extraMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
      }
      if (flag_ != 0) {
        output.writeInt32(2, flag_);
      }
      if (type_ != 0) {
        output.writeInt32(3, type_);
      }
      if (packetType_ != 0) {
        output.writeInt32(4, packetType_);
      }
      if (extraType_ != 0) {
        output.writeInt32(5, extraType_);
      }
      if (version_ != 0) {
        output.writeInt32(6, version_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, content_);
      }
      if (!getSendBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, send_);
      }
      if (!getReceiveBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, receive_);
      }
      if (!getExtraMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, extraMsg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
      }
      if (flag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, flag_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (packetType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, packetType_);
      }
      if (extraType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, extraType_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, version_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, content_);
      }
      if (!getSendBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, send_);
      }
      if (!getReceiveBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, receive_);
      }
      if (!getExtraMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, extraMsg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof msg)) {
        return super.equals(obj);
      }
      msg other = (msg) obj;

      boolean result = true;
      result = result && getMsgId()
          .equals(other.getMsgId());
      result = result && (getFlag()
          == other.getFlag());
      result = result && (getType()
          == other.getType());
      result = result && (getPacketType()
          == other.getPacketType());
      result = result && (getExtraType()
          == other.getExtraType());
      result = result && (getVersion()
          == other.getVersion());
      result = result && getContent()
          .equals(other.getContent());
      result = result && getSend()
          .equals(other.getSend());
      result = result && getReceive()
          .equals(other.getReceive());
      result = result && getExtraMsg()
          .equals(other.getExtraMsg());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (37 * hash) + FLAG_FIELD_NUMBER;
      hash = (53 * hash) + getFlag();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + PACKETTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPacketType();
      hash = (37 * hash) + EXTRATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getExtraType();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + SEND_FIELD_NUMBER;
      hash = (53 * hash) + getSend().hashCode();
      hash = (37 * hash) + RECEIVE_FIELD_NUMBER;
      hash = (53 * hash) + getReceive().hashCode();
      hash = (37 * hash) + EXTRAMSG_FIELD_NUMBER;
      hash = (53 * hash) + getExtraMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg)
        msgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Packet.internal_static_msg_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Packet.internal_static_msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                msg.class, Builder.class);
      }

      // Construct using Packet.msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgId_ = "";

        flag_ = 0;

        type_ = 0;

        packetType_ = 0;

        extraType_ = 0;

        version_ = 0;

        content_ = "";

        send_ = "";

        receive_ = "";

        extraMsg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Packet.internal_static_msg_descriptor;
      }

      public msg getDefaultInstanceForType() {
        return msg.getDefaultInstance();
      }

      public msg build() {
        msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public msg buildPartial() {
        msg result = new msg(this);
        result.msgId_ = msgId_;
        result.flag_ = flag_;
        result.type_ = type_;
        result.packetType_ = packetType_;
        result.extraType_ = extraType_;
        result.version_ = version_;
        result.content_ = content_;
        result.send_ = send_;
        result.receive_ = receive_;
        result.extraMsg_ = extraMsg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof msg) {
          return mergeFrom((msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(msg other) {
        if (other == msg.getDefaultInstance()) return this;
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.getFlag() != 0) {
          setFlag(other.getFlag());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getPacketType() != 0) {
          setPacketType(other.getPacketType());
        }
        if (other.getExtraType() != 0) {
          setExtraType(other.getExtraType());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getSend().isEmpty()) {
          send_ = other.send_;
          onChanged();
        }
        if (!other.getReceive().isEmpty()) {
          receive_ = other.receive_;
          onChanged();
        }
        if (!other.getExtraMsg().isEmpty()) {
          extraMsg_ = other.extraMsg_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object msgId_ = "";
      /**
       * <code>string msgId = 1;</code>
       */
      public String getMsgId() {
        Object ref = msgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public Builder setMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgId_ = value;
        onChanged();
        return this;
      }

      private int flag_ ;
      /**
       * <code>int32 flag = 2;</code>
       */
      public int getFlag() {
        return flag_;
      }
      /**
       * <code>int32 flag = 2;</code>
       */
      public Builder setFlag(int value) {
        
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 flag = 2;</code>
       */
      public Builder clearFlag() {
        
        flag_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 3;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int packetType_ ;
      /**
       * <code>int32 packetType = 4;</code>
       */
      public int getPacketType() {
        return packetType_;
      }
      /**
       * <code>int32 packetType = 4;</code>
       */
      public Builder setPacketType(int value) {
        
        packetType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 packetType = 4;</code>
       */
      public Builder clearPacketType() {
        
        packetType_ = 0;
        onChanged();
        return this;
      }

      private int extraType_ ;
      /**
       * <code>int32 extraType = 5;</code>
       */
      public int getExtraType() {
        return extraType_;
      }
      /**
       * <code>int32 extraType = 5;</code>
       */
      public Builder setExtraType(int value) {
        
        extraType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 extraType = 5;</code>
       */
      public Builder clearExtraType() {
        
        extraType_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 6;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 6;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 6;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 7;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 7;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 7;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 7;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 7;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private Object send_ = "";
      /**
       * <code>string send = 8;</code>
       */
      public String getSend() {
        Object ref = send_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          send_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string send = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSendBytes() {
        Object ref = send_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          send_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string send = 8;</code>
       */
      public Builder setSend(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        send_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string send = 8;</code>
       */
      public Builder clearSend() {
        
        send_ = getDefaultInstance().getSend();
        onChanged();
        return this;
      }
      /**
       * <code>string send = 8;</code>
       */
      public Builder setSendBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        send_ = value;
        onChanged();
        return this;
      }

      private Object receive_ = "";
      /**
       * <code>string receive = 9;</code>
       */
      public String getReceive() {
        Object ref = receive_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          receive_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string receive = 9;</code>
       */
      public com.google.protobuf.ByteString
          getReceiveBytes() {
        Object ref = receive_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          receive_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receive = 9;</code>
       */
      public Builder setReceive(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receive = 9;</code>
       */
      public Builder clearReceive() {
        
        receive_ = getDefaultInstance().getReceive();
        onChanged();
        return this;
      }
      /**
       * <code>string receive = 9;</code>
       */
      public Builder setReceiveBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receive_ = value;
        onChanged();
        return this;
      }

      private Object extraMsg_ = "";
      /**
       * <code>string extraMsg = 10;</code>
       */
      public String getExtraMsg() {
        Object ref = extraMsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          extraMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string extraMsg = 10;</code>
       */
      public com.google.protobuf.ByteString
          getExtraMsgBytes() {
        Object ref = extraMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          extraMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extraMsg = 10;</code>
       */
      public Builder setExtraMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extraMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extraMsg = 10;</code>
       */
      public Builder clearExtraMsg() {
        
        extraMsg_ = getDefaultInstance().getExtraMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string extraMsg = 10;</code>
       */
      public Builder setExtraMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extraMsg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:msg)
    }

    // @@protoc_insertion_point(class_scope:msg)
    private static final msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new msg();
    }

    public static msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<msg>
        PARSER = new com.google.protobuf.AbstractParser<msg>() {
      public msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<msg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<msg> getParserForType() {
      return PARSER;
    }

    public msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014packet.proto\"\252\001\n\003msg\022\r\n\005msgId\030\001 \001(\t\022\014\n" +
      "\004flag\030\002 \001(\005\022\014\n\004type\030\003 \001(\005\022\022\n\npacketType\030" +
      "\004 \001(\005\022\021\n\textraType\030\005 \001(\005\022\017\n\007version\030\006 \001(" +
      "\005\022\017\n\007content\030\007 \001(\t\022\014\n\004send\030\010 \001(\t\022\017\n\007rece" +
      "ive\030\t \001(\t\022\020\n\010extraMsg\030\n \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_descriptor,
        new String[] { "MsgId", "Flag", "Type", "PacketType", "ExtraType", "Version", "Content", "Send", "Receive", "ExtraMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
